# Site settings
name: 听松阁
email: luoyan35714@126.com
author: 听松阁
url: http://www.free163.com
resume_site: http://www.free163.com
github: https://github.com/luoyan35714/
baseurl: "/"
description: Actually, less is more!
meta_description: 个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
#permalink: /:year/:month/:day/:title/
permalink: /:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: luoyan35714

# Build settings
markdown: kramdown

#baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

